"""External solver discovery and run-script generation."""
from __future__ import annotations

import argparse
import json
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path

try:
    from .benchmark_cases import get_case
except ImportError:  # Supports: python em_solver/external_solvers.py ...
    from benchmark_cases import get_case


OPENEMS_MATLAB_PATHS = (
    "/usr/local/share/openEMS/matlab",
    "/usr/local/share/CSXCAD/matlab",
)


OPENEMS_TUTORIALS = {
    "array_l_s_c_x": "/usr/local/share/openEMS/matlab/Tutorials/Patch_Antenna_Phased_Array.m",
    "horn_xband": "/usr/local/share/openEMS/matlab/Tutorials/Horn_Antenna.m",
    "waveguide_family": "/usr/local/share/openEMS/matlab/Tutorials/Rect_Waveguide.m",
    "pec_corner_90": "/usr/local/share/openEMS/matlab/Tutorials/RCS_Sphere.m",
    "wr90_bend_90": "/usr/local/share/openEMS/matlab/examples/waveguide/Rect_Waveguide.m",
}


@dataclass(frozen=True)
class SolverStatus:
    openems: str | None
    appcsxcad: str | None
    octave: str | None
    matlab: str | None
    hfss_ansysedt: str | None

    @property
    def can_run_openems_scripts(self):
        return self.openems is not None and (self.octave is not None or self.matlab is not None)

    @property
    def can_run_hfss(self):
        return self.hfss_ansysedt is not None


def _path_exists_safe(path):
    try:
        return Path(path).exists()
    except (PermissionError, OSError):
        return False


def detect_solvers():
    """Detect external solver executables on PATH."""
    import platform
    if platform.system() == "Windows":
        windows_aedt_candidates = [
            r"C:\Program Files\ANSYS Inc\ANSYS Student\v252\AnsysEM\ansysedtng.exe",
            r"C:\Program Files\ANSYS Inc\ANSYS Student\v252\AnsysEM\ansysedtsv.exe",
            r"C:\Program Files\ANSYS Inc\v252\AnsysEM\ansysedt.exe",
            r"C:\Program Files\ANSYS Inc\v252\AnsysEM\ansysedtng.exe",
        ]
    else:
        windows_aedt_candidates = [
            "/mnt/c/Program Files/ANSYS Inc/ANSYS Student/v252/AnsysEM/ansysedtng.exe",
            "/mnt/c/Program Files/ANSYS Inc/ANSYS Student/v252/AnsysEM/ansysedtsv.exe",
            "/mnt/c/Program Files/ANSYS Inc/v252/AnsysEM/ansysedt.exe",
            "/mnt/c/Program Files/ANSYS Inc/v252/AnsysEM/ansysedtng.exe",
        ]
    hfss = shutil.which("ansysedt")
    if hfss is None:
        hfss = next((path for path in windows_aedt_candidates if _path_exists_safe(path)), None)
    return SolverStatus(
        openems=shutil.which("openEMS"),
        appcsxcad=shutil.which("AppCSXCAD"),
        octave=shutil.which("octave"),
        matlab=shutil.which("matlab"),
        hfss_ansysedt=hfss,
    )


def _matlab_path_setup():
    lines = []
    for path in OPENEMS_MATLAB_PATHS:
        if Path(path).exists():
            lines.append(f"addpath('{path}');")
    return "\n".join(lines)


def write_openems_runner(case_id, output_dir):
    """Write a MATLAB/Octave runner that starts from the closest openEMS tutorial."""
    case = get_case(case_id)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    tutorial = OPENEMS_TUTORIALS.get(case_id)
    if tutorial is None or not Path(tutorial).exists():
        raise ValueError(f"No installed openEMS tutorial/template found for {case_id}")

    runner_path = output_dir / f"run_openems_{case_id}.m"
    metadata_path = output_dir / "openems_case_metadata.json"
    runner_path.write_text(
        "\n".join(
            [
                "% Auto-generated by RFVerificationtool.",
                "% Run with Octave or MATLAB from this directory.",
                "close all; clear; clc;",
                _matlab_path_setup(),
                f"rfvt_case_id = '{case.case_id}';",
                f"rfvt_structure_type = '{case.structure_type}';",
                f"rfvt_reference_tutorial = '{tutorial}';",
                "disp(['RFVT openEMS case: ' rfvt_case_id]);",
                "disp(['Reference tutorial: ' rfvt_reference_tutorial]);",
                "run(rfvt_reference_tutorial);",
                "% Normalize generated openEMS outputs to RFVerificationtool artifacts:",
                "%   sparams.csv, field_near.npz, field_medium.npz, field_far.npz, rcs.csv",
                "% Use em_solver.validation artifact definitions in docs/validation-plan.md.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    metadata_path.write_text(
        json.dumps(
            {
                "case_id": case.case_id,
                "structure_type": case.structure_type,
                "description": case.description,
                "frequency_hz": list(case.frequency_hz),
                "required_artifacts": list(case.required_artifacts),
                "openems_tutorial": tutorial,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return runner_path, metadata_path


def _cmd_status(_args):
    status = detect_solvers()
    print(json.dumps({**asdict(status), "can_run_openems_scripts": status.can_run_openems_scripts, "can_run_hfss": status.can_run_hfss}, indent=2))
    return 0


def _cmd_generate_openems(args):
    runner, metadata = write_openems_runner(args.case, args.output_dir)
    print(f"Wrote {runner}")
    print(f"Wrote {metadata}")
    status = detect_solvers()
    if not status.can_run_openems_scripts:
        print("openEMS script execution is not available because Octave/MATLAB is not on PATH.")
    return 0


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    status_parser = subparsers.add_parser("status", help="Show external solver availability")
    status_parser.set_defaults(func=_cmd_status)

    openems_parser = subparsers.add_parser("generate-openems", help="Generate openEMS MATLAB/Octave runner")
    openems_parser.add_argument("--case", required=True)
    openems_parser.add_argument("--output-dir", required=True, type=Path)
    openems_parser.set_defaults(func=_cmd_generate_openems)
    return parser.parse_args()


def main():
    args = parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())

